app/assets/stylesheets/admin.scss, app/assets/stylesheets/admin/modules/_ckeditor.scss, app/controllers/admin/news_controller.rb, app/javascript/packs/admin.js, app/models/admin_user.rb, app/models/news.rb, app/views/admin/news/_form.html.slim, app/views/admin/news/_news.html.slim, app/views/admin/news/edit.html.slim, app/views/admin/news/index.html.slim, app/views/admin/news/new.html.slim, app/views/admin/news/preview.html.slim, app/views/admin/shared/_sidebar.html.slim, app/views/layouts/admin.html.slim, config/application.rb, config/routes.rb, db/migrate/20171020021027_create_news.rb, db/schema.rb, spec/models/news_spec.rb
=> Admin news

Gemfile, Gemfile.lock, app/controllers/admin/base_controller.rb, app/controllers/admin/news_controller.rb, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/helpers/admin/navtab_helper.rb, app/helpers/admin/page_helper.rb, app/helpers/application_helper.rb, app/models/news.rb, app/views/admin/news/_form.html.slim, app/views/admin/news/edit.html.slim, app/views/admin/news/preview.html.slim, app/views/pages/index.html.slim, config/locales/zh-TW.yml, config/routes.rb, config/settings.yml, db/migrate/20171024172310_add_translation_table_for_news.rb, db/migrate/20171025075751_fix_news_null_violation.rb, db/schema.rb, spec/models/news_spec.rb, spec/rails_helper.rb
Closed #15 
Add multi-language tab on the news, and let users can add translation version inside it.
=> Add multi-language support for news

app/models/site.rb, spec/models/admin_user_spec.rb, spec/models/site_spec.rb, spec/rails_helper.rb
=> Add model test

spec/factories/news.rb, spec/features/admin/admin_news_spec.rb, spec/features/admin/admin_partners_spec.rb
=> Add feature test for news

app/controllers/admin/sponsor_levels_controller.rb, app/controllers/admin/sponsors_controller.rb, app/models/sponsor.rb, app/models/sponsor_level.rb, app/views/admin/shared/_sidebar.html.slim, app/views/admin/sponsor_levels/_form.html.slim, app/views/admin/sponsor_levels/_sponsor_level.html.slim, app/views/admin/sponsor_levels/create.html.slim, app/views/admin/sponsor_levels/destroy.html.slim, app/views/admin/sponsor_levels/edit.html.slim, app/views/admin/sponsor_levels/index.html.slim, app/views/admin/sponsor_levels/new.html.slim, app/views/admin/sponsor_levels/update.html.slim, app/views/admin/sponsors/_form.html.slim, app/views/admin/sponsors/_sponsor.html.slim, app/views/admin/sponsors/edit.html.slim, app/views/admin/sponsors/index.html.slim, app/views/admin/sponsors/new.html.slim, config/routes.rb, db/migrate/20171030020923_create_sponsor_levels.rb, db/migrate/20171030023048_add_translation_table_for_sponsor_levels.rb, db/migrate/20171031022008_create_sponsors.rb, db/migrate/20171031022031_add_translation_table_for_sponsors.rb, db/schema.rb, spec/factories/sponsor_levels.rb, spec/factories/sponsors.rb, spec/features/admin/admin_sponsor_levels_spec.rb, spec/features/admin/admin_sponsors_spec.rb, spec/models/sponsor_level_spec.rb, spec/models/sponsor_spec.rb
=> Sponsor Management

app/assets/stylesheets/application.scss
=> add color rule to text-holder class for non-white hyperlink

Gemfile, Gemfile.lock, app/views/news/index.html.slim, app/views/news/show.html.slim, app/views/shared/_breadcrumb.html.slim, config/breadcrumbs.rb
=> Setup breadcrumb feature

app/views/pages/index/_ticket.html.slim, app/views/shared/_nav.html.slim
=> give ticket section an ID and make the buy ticket button go to that anchor

app/views/shared/_nav.html.slim
=> made the navbar buy ticket button go to the absolute path of KKTIX page

app/controllers/admin/partner_types_controller.rb, app/controllers/admin/partners_controller.rb, app/models/partner.rb, app/models/partner_type.rb, app/views/admin/partner_types/_form.html.slim, app/views/admin/partner_types/_partner_type.html.slim, app/views/admin/partner_types/index.html.slim, app/views/admin/partners/_form.html.slim, app/views/admin/partners/_partner.html.slim, app/views/admin/partners/index.html.slim, db/migrate/20180504141403_add_order_to_partners.rb, db/schema.rb
=> Add order field for partner and partner type

app/controllers/admin/speakers_controller.rb, app/controllers/speakers_controller.rb, app/models/speaker.rb, app/uploaders/avatar_uploader.rb, app/views/admin/speakers/_form.html.slim, app/views/shared/_nav.html.slim, app/views/speakers/index.html.slim, app/views/speakers/show.html.slim, config/breadcrumbs.rb, config/locales/en.yml, config/locales/zh-TW.yml, config/routes.rb, db/migrate/20180521144529_add_title_to_speakers.rb, db/schema.rb
=> Speaker List

Gemfile.lock, app/controllers/admin/partners_controller.rb, app/controllers/admin/sponsors_controller.rb, app/controllers/sponsors_controller.rb, app/models/partner.rb, app/models/sponsor.rb, app/models/sponsor_level.rb, app/views/admin/partners/_form.html.slim, app/views/admin/sponsors/_form.html.slim, app/views/pages/index.html.slim, app/views/shared/_nav.html.slim, app/views/sponsors/index.html.slim, config/breadcrumbs.rb, config/locales/en.yml, config/locales/zh-TW.yml, config/routes.rb, db/migrate/20180627040208_add_description_to_partners.rb, db/migrate/20180627040339_add_description_to_sponsors.rb, db/schema.rb
=> Sponsor Page

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/controllers/agendas_controller.rb, app/views/agendas/show.html.slim
=> Add day tab to agenda@show

app/assets/javascripts/application.js
rewrite arrow function to ES5 style anonymous function
=> Patch application.js: fallback to ES5

app/assets/stylesheets/application.scss, app/controllers/pages_controller.rb, app/views/pages/index.html.slim, app/views/pages/index/_partner.html.slim
see issue #143
current appearance:
- mobile:
- pad:
- desktop:
@elct9620
=> Change sponsors layout in index page

app/assets/stylesheets/application.scss, app/views/agendas/show.html.slim
as title. 
it's a hotfix branch for issue#132
see #158
=> Fix issue#158

app/assets/stylesheets/application.scss, app/views/speakers/show.html.slim
see issue #160 
desktop:
mobile:
=> Fix speaker#show session style

app/assets/stylesheets/modules/_session.scss, app/views/agendas/_time.html.slim, app/views/agendas/show.html.slim
=> Add responsive agenda support

Gemfile, Gemfile.lock, config/initializers/rack_attack.rb
=> Closed #268, Add admin login protected

app/views/shared/_nav.html.slim, config/locales/zh-TW.yml
=> Closed #291, Add watch now to navigation

app/views/agendas/show.html.slim, app/views/speakers/index.html.slim, app/views/sponsors/index.html.slim, config/locales/en.yml, config/locales/zh-TW.yml
=> Add page description for SEO

config/locales/en.yml
=> add translation to CoC button

app/views/shared/_nav.html.slim
=> Fix navbar not hidden disable feature

app/views/admin/speakers/_form.html.slim
=> Set speaker photo as option to prevent re-uploading avatar

config/locales/en.yml, config/locales/zh-TW.yml
As title. I've not added the pre-register description for now, because the kktix preregister page is not ready yet. But we should update the base template first nonetheless.
=> Change event track to pre-register stuff

config/locales/zh-TW.yml
=> locale wording fix

config/locales/zh-TW.yml
Reverts TGDF/official-site#314
=> Revert "locale wording fix"

config/locales/en.yml, config/locales/zh-TW.yml
as title, now the pre-register is ready, updating the description of the div
=> make the pre-register block official

config/locales/en.yml, config/locales/zh-TW.yml
=> change survey CTA desc
